---
- name: Gathering Facts from AS400
  hosts: all
  vars:
    ansible_python_interpreter: /QOpenSys/pkgs/bin/python3
  connection: ssh
  collections:
    - ibm.power_ibmi
  gather_facts: true
  tasks:
  
    - name: Return factd
      ibm.power_ibmi.ibmi_cl_command:
        cmd: uname
