---
- name: Gathering Facts from AS400
  hosts: all
  vars:
    ansible_python_interpreter: /QOpenSys/pkgs/bin/python3
  connection: ssh
  collections:
    - ibm.power_ibmi
  gather_facts: true
  tasks:
    - block:
      - name: Display a system value
        ibmi_sysval:
          sysvalue:
            - {'name':'qccsid'}
        register: dspsysval_ccsid_result
  
      - name: Display the returned parameters
        debug:
          msg: "{{ dspsysval_ccsid_result }}"
      
