---
- name: Copiar binarios Local to Remote Agente NewRelic
  hosts: all
  become: false
  tasks:
  
    - name: Copy File
      ansible.windows.win_copy:
        src: /home/ansible
        dest: C:\Automatizacion_Ansible\newrelic-infra.rar
        remote_src: true
      when: ansible_facts.hostname == 'PRUEBA'
