---
- name: Copiar binarios Local to Remote Agente NewRelic
  hosts: all
  become: false
  tasks:
  
    - name: Copy File
      ansible.windows.win_copy:
        src: /root/Automatizacion_Ansible/Automatizacion_Ansible
        dest: C:\Automatizacion_Ansible\newrelic-infra.msi
        remote_src: true
      when: ansible_facts.hostname == 'PRUEBA'
