---
- name: Habilitar tareas de cierre
  hosts: all
  become: false
  gather_facts: true
  tasks:
  
    - name: Get information about a task in the root folder
      community.windows.win_scheduled_task_stat:
        name: pivote
      register: task_state

    - name: Get information about a task in the root folder
      community.windows.win_scheduled_task_stat:
        name: '{{ item }}' 
      loop:
        - CSP_ScheduledSettlements_06am
        - pivote
      register: task

    - name: Log de tareas
      debug:
        msg: "{{ task }}"

    - name: bloque para activar tareas
      block:
        - name: activar de tareas
          ansible.windows.win_powershell:
            script: |
              Enable-ScheduledTask -TaskName '{{ item }}' 
          loop:
            - CSP_ScheduledSettlements_06am
            - pivote
          register: task_post

        - name: Log de tareas activas
          debug:
            msg: "{{ task_post }}"

        - name: stop processing task
          meta: end_play
   
      when: task_state.state.status == "TASK_STATE_DISABLED"

    - name: bloque para desactivar tareas
      block:
        - name: desactivar tareas
          ansible.windows.win_powershell:
            script: |
              Disable-ScheduledTask -TaskName '{{ item }}' 
          loop:
            - CSP_ScheduledSettlements_06am
            - pivote
          register: task_post

        - name: Log de tareas incativas
          debug:
            msg: "{{ task_post }}"

        - name: stop processing task
          meta: end_play
   
      when: task_state.state.status == "TASK_STATE_READY"

   
