---
- name: Habilitar tareas de cierre
  hosts: all
  become: false
  gather_facts: true
  tasks:
  
    - name: Get information about a task in the root folder
      community.windows.win_scheduled_task_stat:
        name: CSP_ScheduledSettlements_06am
      register: task_state

    - name: bloque para activar tareas
      block:
        - name: Reporte tareas programadas
          ansible.windows.win_powershell:
            script: |
              Enable-ScheduledTask -TaskName '{{ item }}' 
          loop:
            - CSP_ScheduledSettlements_06am
          register: task_post

        - name: stop processing task
          meta: end_play
   
      when: task_stat.state.status == "TASK_STATE_DISABLED"

    - name: Log de tareas activas
      debug:
        msg: "{{ task_post }}"
