---
- name: Habilitar tareas de cierre
  hosts: all
  become: false
  gather_facts: true
  tasks:
  
    - name: Get information about a task in the root folder
      community.windows.win_scheduled_task_stat:
        name: pivote
      register: task_state

    - name: Reporte tareas programadas
      ansible.windows.win_powershell:
        script: |
          Get-ScheduledTask | Where-Object -Property TaskName -match '{{ item }}' | Select-Object -Property TaskName,State | ConvertTo-Json >> C:\Automatizacion_Ansible\Revision_Ambiente\Estado_Tareas_Programadas\tareaProgramada_{{ ansible_date_time.date }}.json
      loop:
        - CSP_ScheduledSettlements_06am
        - pivote
     - name: get content
       win_shell: 'type C:\Automatizacion_Ansible\Revision_Ambiente\Estado_Tareas_Programadas\tareaProgramada_{{ ansible_date_time.date }}.json'  
       register: content

    - name: Log de tareas activas
      debug:
        msg: "{{ content.stdout }}"

    - name: bloque para activar tareas
      block:
        - name: activar de tareas
          ansible.windows.win_powershell:
            script: |
              Enable-ScheduledTask -TaskName '{{ item }}' 
          loop:
            - CSP_ScheduledSettlements_06am
            - pivote
          register: task_post

        - name: Log de tareas activas
          debug:
            msg: "{{ task_post }}"

        - name: stop processing task
          meta: end_play
   
      when: task_state.state.status == "TASK_STATE_DISABLED"

    - name: bloque para desactivar tareas
      block:
        - name: desactivar tareas
          ansible.windows.win_powershell:
            script: |
              Disable-ScheduledTask -TaskName '{{ item }}' 
          loop:
            - CSP_ScheduledSettlements_06am
            - pivote
          register: task_post

        - name: Log de tareas incativas
          debug:
            msg: "{{ task_post }}"

        - name: stop processing task
          meta: end_play
   
      when: task_state.state.status == "TASK_STATE_READY"

   
