---
- name: Habilitar tareas de cierre
  hosts: all
  become: false
  gather_facts: true
  tasks:

    - name: Reporte tareas programadas
      ansible.windows.win_powershell:
        script: |
          Get-ScheduledTask | Where-Object -Property TaskName -match '{{ item }}' | Select-Object -Property TaskName,State
      loop:
        - CSP_ScheduledSettlements_06am
      register: task_state

    - name: Log de tareas activas
      debug:
        msg: |
          "Tareas: {{ task_state }}"
