---
- name: HOLDEAR TRABAJOS IBM
  hosts: all
  vars:
    ansible_python_interpreter: /QOpenSys/pkgs/bin/python3
    JOB_NAME: CMC499
  collections:
    - ibm.power_ibmi
  connection: ssh
  gather_facts: false
  tasks:

    - name: INFORMACIÓN ESTADO INICIAL TAREA CM499
      ibmi_sql_query:
        sql: "SELECT JOB_NAME_SHORT,JOB_STATUS FROM TABLE(QSYS2.ACTIVE_JOB_INFO()) B WHERE JOB_NAME_SHORT = '{{ JOB_NAME }}'"
      register: select_job_result

    - name: Get status of a list of jobs
      ibm.power_ibmi.ibmi_job:
        user: "QSECOFR"
        type: "*BATCH"
      register: holded_job_status

    - name: ESTADO TAREA 
      debug:
        var: holded_job_status

        
