---
- name: HOLDEAR TRABAJOS IBM
  hosts: all
  vars:
    ansible_python_interpreter: /QOpenSys/pkgs/bin/python3
    JOB_NAME: CMC500
  collections:
    - ibm.power_ibmi
  connection: ssh
  gather_facts: false
  tasks:

    - name: INFORMACIÓN ESTADO INICIAL TAREA CM499
      ibmi_sql_query:
        sql: "SELECT JOB_NAME_SHORT,JOB_STATUS FROM TABLE(QSYS2.ACTIVE_JOB_INFO()) B WHERE JOB_NAME_SHORT = '{{ JOB_NAME }}'"
      register: select_job_result

    - name: HOLDEAR TRABAJO CM499
      ibmi_cl_command:
        cmd: "HLDJOB JOB({{ JOB_NAME }})"
      when: select_job_result.row | selectattr('JOB_STATUS', '!=', 'HLD') | map(attribute='JOB_STATUS') | list
      failed_when:
        - select_job_result.row | selectattr('JOB_STATUS', '==', 'DLYW') | map(attribute='JOB_STATUS') | list
      tags:
      - holdear_trabajo

    - name: COMPROBAR ESTADO HOLDEADO CM499
      ibmi_sql_query:
        sql: "SELECT JOB_NAME_SHORT,JOB_STATUS FROM TABLE(QSYS2.ACTIVE_JOB_INFO()) B WHERE JOB_NAME_SHORT = '{{ JOB_NAME }}'"
      register: holded_job_status

    - name: ESTADO TAREA 
      debug:
        var: holded_job_status.row

        