---
- name: Prueba
  hosts: all
  gather_facts: yes
  tasks: 
    #- name: stop processing task
     # meta: end_play
      
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts.hostname
      when: ansible_facts.hostname == 'EC2AMAZ-QNL0RSF'

    - name: Get Disks Sizes
      ansible.windows.win_powershell:
        script: |
           Get-WMIObject  -Class Win32_LogicalDisk | Where-Object {$_.DriveType -eq 3}  `
           | Select-Object @{n="Unidad";e={($_.Name)}}, 
                    @{n="Etiqueta";e={($_.VolumeName)}}, 
                    @{n='Tamaño (GB)';e={"{0:n2}" -f ($_.size/1gb)}}, 
                    @{n='Libre (GB)';e={"{0:n2}" -f ($_.freespace/1gb)}}, 
                    @{n='% Libre';e={"{0:n2}" -f ($_.freespace/$_.size*100)}} >> C:\Users\AppData\Local\Temp\ansibleLogs\services_logs_{{ansible_date_time.date}}.txt
      register: disk_sizes_var

    - debug:
        msg:
          - "Tamaños Discos: {{ disk_sizes_var.output }}"

