---
- name: Prueba
  hosts: all
  gather_facts: yes
  tasks: 
    #- name: stop processing task
     # meta: end_play
      
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts
      when: ansible_facts.hostname == 'EC2AMAZ-QNL0RSF'  

