---
- name: Prueba
  hosts: all
  gather_facts: yes
  tasks: 
    - name: Display all variables/facts known for a host
      ansible.builtin.debug:
        var: hostvars[inventory_hostname]
        verbosity: 4

    - name: stop processing task
      meta: end_play
      
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts
