---
- name: Prueba
  hosts: all
  gather_facts: yes
  tasks: 
    - name: Get Disks Sizes
      ansible.windows.win_powershell:
        script: |
           Get-WMIObject  -Class Win32_LogicalDisk | Where-Object {$_.DriveType -eq 3}  `
           | Select-Object @{n="Unidad";e={($_.Name)}}, 
                    @{n="Etiqueta";e={($_.VolumeName)}}, 
                    @{n='Tamaño (GB)';e={"{0:n2}" -f ($_.size/1gb)}}, 
                    @{n='Libre (GB)';e={"{0:n2}" -f ($_.freespace/1gb)}}, 
                    @{n='% Libre';e={"{0:n2}" -f ($_.freespace/$_.size*100)}} | ConvertTo-Json >> C:\Users\AppData\Local\Temp\ansibleLogs\services_logs_{{ ansible_date_time.iso8601 }}.json
      register: disk_sizes_var

    - debug:
        msg:
          - "Tamaños Discos: {{ disk_sizes_var.output }}"


    - name: Ansible fact 
      debug:
        msg: {{ ansible_date_time }}

