---
- name: Crear backup Base de Datos
  hosts: all
  become: false
  tasks:
    - name: Create backup DataBase 
      ansible.windows.win_powershell:
        script: |
          Restore-SqlDatabase -ServerInstance "PRUEBA" -Database "Sales" -BackupFile "C:\Sql\Sales.bak"
