---
- name: Proceso de revisión Pool de IIS
  hosts: all
  gather_facts: yes
  tasks:

- name: Create Directory
  ansible.windows.win_file:
    path: D:\Automatizacion_Ansible\Revision_Ambiente\Pool_IIS
    state: directory

- name: Reporte Pool IIS
  ansible.windows.win_powershell:
    script: |
      Get-IISAppPool | Select-Object -Property Name,Status | ConvertTo-Json >> D:\Automatizacion_Ansible\Revision_Ambiente\Pool_IIS\reportePoolIIS_{{ansible_date_time.date}}.json
  
