---

- name: Validación Servicios Consolas Active Directory

  hosts: all

  gather_facts: false

  tasks:

 

    - name: Validar el estado del servicio

      ansible.windows.win_service:

        name: "{{ item }}"

      loop:

        - RpcSs

        - RemoteRegistry

        - iprip

        - RemoteAccess

        - DPS

        - PolicyAgent

        - Spooler

      register: result

      failed_when: result is not defined

    - name: Salida de estado de los servicios
      ansible.windows.win_powershell:
        script: |
          get-service "{{ item }}" | select Displayname,Status,ServiceName,Can*
      register: results
      failed_when: results is not defined
      loop:
        - RpcSs

        - RemoteRegistry

        - iprip

        - RemoteAccess

        - DPS

        - PolicyAgent

        - Spooler

    - debug:
        msg:  {{ results }} 

 

    - name: Si el servicio esta 'stopped' cambiar a 'started'

      ansible.windows.win_service:

        name: "{{ result.results[ansible_loop.index0 - 1].name }}"

        state: started

      when: "'stopped' in result.results"

      loop: "{{ result.results }}"