---
- name: Crear backup slq
  hosts: all
  become: false
  tasks:
    - name: Check DB connection
      community.general.mssql_script:
        login_user: "Administrator"
        login_password: "AnsibleMT23$"
        login_host: "PruebaVM"
        login_port: 1433 
        db: Sales
        script: "SELECT 1"
