---
- name: Crear backup Base de Datos
  hosts: all
  become: false
  tasks:
    - name: Create backup DataBase 
      ansible.windows.win_powershell:
        script: |
           BAckup-SqlDatabase -ServerInstance "PruebaVM" -Database "Sales" -BackupAction Database
