---
- name: Crear backup slq
  hosts: all
  become: false
  tasks:
    - name: Create striped full database backup in default dir
      lowlydba.sqlserver.backup:
      sql_instance: PruebaVM
      database: Sales
      type: full
      file_count: 8
