---
- name: State programmed tasks
  hosts: all
  gather_facts: yes
  tasks:
  
  # Status tareas programadas
  - name: Create Directory
    ansible.windows.win_file:
      path: C:\Automatizacion_Ansible\Revision_Ambiente\Estado_Tareas_Programadas
      state: directory
  
  - name: Report state programmed tasks
    ansible.windows.win_powershell:
      script: |
        $currentDate = Get-Date -Format "dd-MM-yyyy_HH:mm"
        Get-ScheduledTask | Where-Object -Property TaskName -match '{{ SchduledTask_Name }}' | Select-Object -Property TaskName,State | ConvertTo-Json >> C:\Automatizacion_Ansible\Revision_Ambiente\Estado_Tareas_Programadas\reporteTareasProgramadas_$currentDate.json

    
