# Windows Disks States
---
- name: Get Current Windows Disks State
  hosts: all
  gather_facts: false
  tasks:

    - name: Check status
      ansible.windows.win_powershell:
        script: |
          Get-Volume | select DriveLetter,HealthStatus,Size,SizeRemaining
      register: output_var

    - debug:
        msg:
          - "Disco: {{ output_var.output[ansible_loop.index0 - 1].DriveLetter }}"
          - "Estado: {{ output_var.output[ansible_loop.index0 - 1].HealthStatus }}"
          - "Size MB: {{ output_var.output[ansible_loop.index0 - 1].Size }}"
          - "SizeRemaining MB: {{ output_var.output[ansible_loop.index0 - 1].SizeRemaining }}"
      loop: "{{ output_var.output }}"
      loop_control:
        extended: true
        label: "{{ ansible_loop.index0 }}"
