- name: Estado de los servicios CSP
  hosts: all
  gather_facts: yes
  tasks:
  
    - name: Create Directory
      ansible.windows.win_file:
        path: D:\Automatizacion_Ansible\Revision_Ambiente\Servicios
        state: directory
    
    - name: Reporte Servicios Activos
      ansible.windows.win_powershell:
        script: |
          Get-Service | Where-Object -Property Name -match "{{ item }}" | Where-Object -Property Status -match "Running" | Select-Object -Property Name,Status | ConvertTo-Json >> D:\Automatizacion_Ansible\Revision_Ambiente\Servicios\ServiciosRunning_{{ ansible_date_time.date }}.json
      loop: "{{ servicios_csp }}"
    
    - name: Reporte Servicios Detenidos
      ansible.windows.win_powershell:
        script: |
          $countStoppedServices = Get-Service | Where-Object -Property Name -match "{{ item }}" | Where-Object -Property Status -match "Stopped"
          if ( $countStoppedServices -eq $null ){ echo "No hay servicios detenidos" }else{ Get-Service | Where-Object -Property Name -match "{{ item }}" | Where-Object -Property Status -Match "Stopped" | Select-Object Name,Status | ConvertTo-Json >> D:\Automatizacion_Ansible\Revision_Ambiente\Servicios\ServiciosStopped_{{ ansible_date_time.date }}.json }
      loop: "{{ servicios_csp }}"





