---
- name: Estado de los discos
  hosts: all
  gather_facts: yes
  tasks:

  # Estado de los discos
  
    - name: Create Directory
      ansible.windows.win_file:
        path: D:\Automatizacion_Ansible\Revision_Ambiente\Estado_Tareas_Programadas
        state: directory

    - name: Reporte tareas programadas
      ansible.windows.win_powershell:
        script: |
          Get-ScheduledTask | Where-Object -Property TaskName -match '{{ item }}' | Select-Object -Property TaskName,State | ConvertTo-Json >> D:\Automatizacion_Ansible\Revision_Ambiente\Estado_Tareas_Programadas\tareaProgramada_{{ ansible_date_time.date }}.json
      loop:
        - CSP_ScheduledSettlements_06am
      register: task_state
    
    - debug:
        msg: {{ task_state }} 
    
    - name: Enable Programmed Tasks
      ansible.windows.win_powershell:
        script: |
          Enable-ScheduledTask -TaskName '{{ item }}'
      loop:
        - CSP_ScheduledSettlements_06am



