---
- name: Estado de los discos
  hosts: all
  gather_facts: yes
  tasks:

  # Estado de los discos
  
  - name: Generating file
    ansible.windows.win_powershell:
      script: |
        Get-WmiObject win32_logicaldisk | Format-Table DeviceId, MediaType, @{n="Size";e={[math]::Round($_.Size/1GB,2)}},@{n="FreeSpace";e={[math]::Round($_.FreeSpace/1GB,2)}}, @{n="UsedSpace";e={[math]::Round((($_.Size-$_.FreeSpace)/1GB),2)}} | select DriveLetter,HealthStatus,Size,SizeRemaining | ConvertTo-Json >> C:\Users\AppData\Local\Temp\ansibleLogs\disk_info_{{ansible_date_time.date}}.json

  - name: Check status
    ansible.windows.win_powershell:
      script: |
        Get-Volume | select DriveLetter,HealthStatus,Size,SizeRemaining 
    register: output_var
  
  - debug:
      msg:
        - "Disco: {{ output_var.output[ansible_loop.index0 - 1].DriveLetter }}"
        - "Estado: {{ output_var.output[ansible_loop.index0 - 1].HealthStatus }}"
        - "Size MB: {{ output_var.output[ansible_loop.index0 - 1].Size }}"
        - "SizeRemaining MB: {{ output_var.output[ansible_loop.index0 - 1].SizeRemaining }}"
    loop: "{{ output_var.output }}"
    loop_control:
      extended: true
      label: "{{ ansible_loop.index0 }}"



