---
- name: Tareas de cierre
  hosts: all
  become: false
  gather_facts: true
  tasks:
    - name: Ensure user bob is present
      ansible.windows.win_user:
        name: bob
        password: B0bP4ssw0rd
        state: present
        groups:
          - Users
