---
- name: Hardening over Windows Server Machine
  hosts: all
  become: false
  gather_facts: false
  vars:
    VM_HOSTNAME: PruebaVM
    GUEST_USER_NEW_NAME: Developer
  tasks:

    #1 Cambiar nombre de host
    - name: Cambiar nombre del host virtual
      win_hostname:
        name: "{{ VM_HOSTNAME }}"

    - name: Cambiar nombre usuario Guest
      ansible.windows.win_powershell:
        script: |
          Rename-LocalUser -Name "Guest" -NewName "{{ GUEST_USER_NEW_NAME }}"

    #2 Establecer Zona horaria 
    - name: Establecer zona horaria "(UTC-4:30) Caracas"
      community.windows.win_timezone:
        timezone: Atlantic Standard Time
    
    #3 Colocar Online todos los discos desconectados
    - name: Cambiando estado de discos (Online)
      ansible.windows.win_powershell:
        script: |
          Get-Disk | Where-Object IsOffline -Eq $True | Set-Disk -IsOffline $False

    #4 Desactivar Firewall (Dominio, Público y Privado)
    - name: Desactivar Firewall
      win_firewall:
        state: disabled
        profiles:
        - Domain
        - Public
        - Private
      tags: disable_firewall

    #5 Parar Servicio Wndows Update
    - name: Desactivar y Parar Windows Update Service
      ansible.windows.win_powershell:
        script: |
          sc.exe config wuauserv start=disabled
          sc.exe stop wuauserv
          REG.exe QUERY HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\wuauserv /v Start

    #6 Modificar tiempo de arranque
    - name: Modificar tiempo de arranque
      ansible.windows.win_powershell:
        script: |
          bcdedit /timeout 5

    #7 Modificar tamaño de log Event Viewer
    - name: Modificar tamaño de log Event Viewer
      ansible.windows.win_powershell:
        script: |
          Limit-EventLog -LogName "{{ item.log_name }}" -MaximumSize 20480KB
      loop:
        - { log_name: Application }
        - { log_name: Security }
        - { log_name: System }

    - name: Reinicio requerido 
      ansible.windows.win_reboot:

