---
- name: Hardening over Windows Server Machine
  hosts: windows
  become: false
  gather_facts: false
  vars:
    VM_HOSTNAME: PruebaVM
    GUEST_USER_NEW_NAME: Developer
  tasks:

    #1 Cambiar nombre de host
    - name: Cambiar nombre del host virtual
      win_hostname:
        name: "{{ VM_HOSTNAME }}"

    #2 Agregar grupos administradores 
    - name: Agregar grupos administradores
      win_group_membership:
        name: Grupo de usuarios adm
        members:
          - INTRA\Domain Admins
          - INTRA\G_ADM_AdministradoresServidores
          - INTRA\G_ADM_DisoverHP
          - INTRA\SVC_TWScheduler_Pro
        state: present

    - name: Cambiar nombre usuario Guest
      ansible.windows.win_powershell:
        script: |
          Rename-LocalUser -Name "Guest" -NewName "{{ GUEST_USER_NEW_NAME }}"

    #3 Establecer Zona horaria 
    - name: Establecer zona horaria "(UTC-4:30) Caracas"
      win_timezone:
        timezone: Atlantic Standard Time
    
    #4 Colocar Online todos los discos desconectados
    - name: Cambiando estado de discos (Online)
      ansible.windows.win_powershell:
        script: |
          Get-Disk | Where-Object IsOffline -Eq $True | Set-Disk -IsOffline $False

    #5 Desactivar Firewall (Dominio, Público y Privado)
    - name: Desactivar Firewall
      win_firewall:
        state: disabled
        profiles:
        - Domain
        - Public
        - Private
      tags: disable_firewall

    #6 Parar Servicio Wndows Update
    - name: Desactivar y Parar Windows Update Service
      ansible.windows.win_powershell:
        script: |
          sc.exe config wuauserv start=disabled
          sc.exe stop wuauserv
          REG.exe QUERY HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\wuauserv /v Start

    #7 Modificar tiempo de arranque
    - name: Modificar tiempo de arranque
      ansible.windows.win_powershell:
        script: |
          bcdedit /timeout 5

    #8 Modificar tamaño de log Event Viewer
    - name: Modificar tamaño de log Event Viewer
      ansible.windows.win_powershell:
        script: |
          Limit-EventLog -LogName "{{ item.log_name }}" -MaximumSize 20480KB
      loop:
        - { log_name: Application }
        - { log_name: Security }
        - { log_name: System }

    #9 Dejar solo el grupo Administradores en Allow log on locally
    - name: Permitir solo "Administradores" en 'Allow Log on Locally'
      win_user_right:
        name: SeDenyInteractiveLogonRight
        users:
        - Guest
        - Users
        - Backup
        - Operators
        - Power Users
        action: set
      ignore_errors: true

    - name: Reinicio requerido 
      ansible.windows.win_reboot:

